- hosts: localhost
  connection: local
  vars:
    neovim_osc52_enabled: true
  roles:
    - common_core
    - bash_core
    - tmux_core
    - fzf_core
    - cargo_core
    - neovim_core
    - croc
    - rclone
