- name: Execute core kitty tasks
  include_role:
    name: core_kitty

- name: Copy thinkpad kitty configuration
  ansible.posix.synchronize:
    src: "config/"
    dest: "~/.config/kitty"
    times: true
    checksum: true
