- hosts: localhost
  connection: local
  vars:
    neovim_osc52_enabled: true
  roles:
    - { role: common,  tags: common  }
    - { role: bash,    tags: bash    }
    - { role: tmux,    tags: tmux    }
    - { role: fzf,     tags: fzf     }
    - { role: neovim,  tags: neovim  }
    - { role: croc,    tags: croc    }
    - { role: rclone,  tags: rclone  }
    - { role: scripts, tags: scripts }
