- name: Execute core neovim tasks
  include_role:
    name: neovim_core

- name: Copy thinkpad neovim configuration
  ansible.posix.synchronize:
    src: "config/"
    dest: "~/.config/nvim"
    group: false
    times: false
    checksum: true
