- name: Execute core neovim tasks
  include_role:
    name: core_neovim

- name: Copy neovim configuration
  ansible.posix.synchronize:
    src: "config/"
    dest: "~/.config/nvim/"
    archive: false
    times: false
