#!/bin/sh
usage() {
  echo 'Usage: newline (add | remove) [file] ...'
}

if [ $# -eq 0 ]; then
  usage && exit 1
fi

if [ "$1" = 'add' ]; then
  shift && perl -pi -e '$_ .= "\n" if eof && !/\n\z/' "$@"
elif [ "$1" = 'remove' ]; then
  shift && perl -pi -e 'chomp if eof' "$@"
else
  usage && exit 1
fi
