#!/usr/bin/env racket
;; vim: set filetype=racket :
#lang racket/base
(require racket/list
         racket/string
         racket/system)

((λ ()
   (system (string-join (first (shuffle (combinations '("-a" "-l" "-F"))))
                        #:before-first "/usr/bin/sl "))
   (void)))
